import { LocalizedNavLink } from "@/components/LocalizedNavLink";
import { usePageMetadata } from "@/hooks/usePageMetadata";
import { LegalPageWrapper } from "@/components/LegalPageWrapper";
import { EmailWithFallback } from "@/components/EmailWithFallback";

const Disclaimer = () => {
  usePageMetadata({
    title: "Disclaimer | CalorieVision",
    description: "Read the CalorieVision disclaimer clarifying that all nutrition estimates are approximate and strictly educational.",
    path: "/disclaimer",
  });

  return (
    <LegalPageWrapper>
      <div className="mb-4 text-sm text-primary md:text-base">Legal</div>
      <h1 className="mb-6 text-3xl font-bold md:text-4xl">Disclaimer</h1>

      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        <strong className="text-foreground">Last updated: December 31, 2025</strong>
      </p>

      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        The information provided on CalorieVision (the "Service") is for general informational and educational purposes only. Please read this disclaimer carefully before using our Service.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-4 text-xl font-semibold">No Medical or Professional Advice</h2>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        <strong className="text-foreground">THIS IS NOT MEDICAL ADVICE.</strong>
      </p>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        CalorieVision does not provide medical, nutritional, dietary, or health advice. All calorie estimates, food analyses, and nutrition-related content generated by the application are approximate and educational.
      </p>
      <p className="mb-2 text-sm text-muted-foreground md:text-base">
        <strong className="text-foreground">Important:</strong>
      </p>
      <ul className="mb-4 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li>The Service is NOT a substitute for professional medical advice, diagnosis, or treatment</li>
        <li>Always seek the advice of a qualified healthcare professional, registered dietitian, or nutritionist before making any dietary, nutritional, or health-related decisions</li>
        <li>Never disregard professional medical advice or delay seeking it because of something you have seen on CalorieVision</li>
        <li>If you have a medical emergency, call your doctor or emergency services immediately</li>
      </ul>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        <strong className="text-foreground">The nutritional information provided is an estimation only. Accuracy is not guaranteed.</strong>
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-4 text-xl font-semibold">AI Technology Limitations</h2>
      <p className="mb-2 text-sm text-muted-foreground md:text-base">
        CalorieVision uses artificial intelligence (AI) and image recognition technology to estimate nutritional content. You should be aware that:
      </p>
      <ul className="mb-6 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li>AI technology has inherent limitations and may produce errors</li>
        <li>Food recognition depends on image quality, lighting, and visibility</li>
        <li>Portion size estimation is approximate and may vary significantly</li>
        <li>The AI cannot detect all ingredients, especially hidden or mixed components</li>
        <li>Results should be used as a general guide only, not as precise measurements</li>
      </ul>

      <hr className="my-8 border-border" />

      <h2 className="mb-4 text-xl font-semibold">Allergy and Dietary Warnings</h2>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        <strong className="text-foreground">IMPORTANT SAFETY NOTICE:</strong>
      </p>
      <ul className="mb-4 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li>CalorieVision CANNOT reliably detect allergens in food</li>
        <li>The Service may NOT identify all ingredients present in a meal</li>
        <li>Do NOT rely on this Service if you have food allergies, intolerances, or specific dietary restrictions</li>
        <li>Hidden ingredients, cross-contamination, and preparation methods cannot be detected from images</li>
        <li>If you have allergies or dietary restrictions, always verify ingredients directly with the food source</li>
      </ul>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        <strong className="text-foreground">CalorieVision assumes no responsibility for allergic reactions or adverse health effects.</strong>
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-4 text-xl font-semibold">Accuracy of Information</h2>
      <p className="mb-2 text-sm text-muted-foreground md:text-base">
        While we aim to provide useful and up-to-date information, CalorieVision makes NO guarantees regarding:
      </p>
      <ul className="mb-4 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li>Accuracy of calorie estimates</li>
        <li>Completeness of nutritional information</li>
        <li>Reliability of food identification</li>
        <li>Suitability for any particular purpose</li>
        <li>Correctness of portion size estimates</li>
      </ul>
      <p className="mb-2 text-sm text-muted-foreground md:text-base">
        Food recognition and calorie estimation are based on visual analysis and common assumptions. Results may vary significantly depending on:
      </p>
      <ul className="mb-6 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li>Portion size and serving amount</li>
        <li>Actual ingredients used</li>
        <li>Preparation and cooking methods</li>
        <li>Image quality and lighting</li>
        <li>Regional variations in recipes</li>
      </ul>

      <hr className="my-8 border-border" />

      <h2 className="mb-4 text-xl font-semibold">Not for Medical Conditions</h2>
      <p className="mb-2 text-sm text-muted-foreground md:text-base">
        CalorieVision is NOT suitable for managing medical conditions including but not limited to:
      </p>
      <ul className="mb-4 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li>Diabetes or blood sugar management</li>
        <li>Eating disorders (anorexia, bulimia, binge eating)</li>
        <li>Kidney disease requiring protein monitoring</li>
        <li>Heart disease requiring sodium restriction</li>
        <li>Any condition requiring precise nutritional tracking</li>
      </ul>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        If you have any medical condition, consult your healthcare provider before using this Service.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-4 text-xl font-semibold">Use at Your Own Risk</h2>
      <p className="mb-2 text-sm text-muted-foreground md:text-base">
        Your use of the Service is entirely at your own risk. CalorieVision and its operators, owners, employees, and affiliates shall NOT be held liable for any:
      </p>
      <ul className="mb-4 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li>Loss, injury, or damage of any kind</li>
        <li>Health consequences from relying on estimates</li>
        <li>Decisions made based on the information provided</li>
        <li>Allergic reactions or adverse health effects</li>
        <li>Direct, indirect, incidental, or consequential damages</li>
      </ul>
      <p className="mb-2 text-sm text-muted-foreground md:text-base">
        You acknowledge that you are solely responsible for:
      </p>
      <ul className="mb-6 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li>Verifying nutritional information independently</li>
        <li>Making your own health and dietary decisions</li>
        <li>Consulting professionals when needed</li>
      </ul>

      <hr className="my-8 border-border" />

      <h2 className="mb-4 text-xl font-semibold">External Links</h2>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        The Service may contain links to third-party websites or services. We do not control, endorse, or assume responsibility for the content, privacy policies, or practices of any third-party sites or services.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-4 text-xl font-semibold">Changes to This Disclaimer</h2>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        We may update this Disclaimer from time to time. Changes will be posted on this page with an updated revision date. Your continued use of the Service after changes constitutes acceptance of the updated Disclaimer.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-4 text-xl font-semibold">Contact Us</h2>
      <p className="mb-2 text-sm text-muted-foreground md:text-base">
        If you have any questions about this Disclaimer, please contact us:
      </p>
      <ul className="mb-6 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li><EmailWithFallback showLabel /></li>
        <li><strong className="text-foreground">Website:</strong>{" "}<a href="https://calorievision.online" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">calorievision.online</a></li>
        <li><strong className="text-foreground">Contact Page:</strong>{" "}<LocalizedNavLink to="/contact" className="text-primary hover:underline">calorievision.online/contact</LocalizedNavLink></li>
      </ul>

      <hr className="my-8 border-border" />

      <p className="text-sm italic text-muted-foreground md:text-base">
        By using CalorieVision, you acknowledge that you have read, understood, and agree to this Disclaimer.
      </p>
    </LegalPageWrapper>
  );
};

export default Disclaimer;
