import { usePageMetadata } from "@/hooks/usePageMetadata";
import { LegalPageWrapper } from "@/components/LegalPageWrapper";

const Terms = () => {
  usePageMetadata({
    title: "Terms & Conditions | CalorieVision",
    description: "Read the terms and conditions for using CalorieVision.",
    path: "/terms",
  });

  return (
    <LegalPageWrapper>
      <div className="mb-4 text-sm text-primary md:text-base">Legal</div>
      <h1 className="mb-6 text-3xl font-bold md:text-4xl">Terms & Conditions</h1>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        <strong>Last updated: December 31, 2025</strong>
      </p>

      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        Welcome to CalorieVision. By accessing or using this website and its services, you agree to be bound by the following Terms and Conditions. If you do not agree with any part of these terms, please do not use the website.
      </p>

      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        These Terms apply to all visitors, users, and others who access or use the Service worldwide, including users in the European Union, European Economic Area, United Kingdom, United States, and other jurisdictions.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">1. Acceptance of Terms</h2>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        By accessing and using CalorieVision, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions and our Privacy Policy. If you do not agree with any part of these terms, you must not use our Service.
      </p>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        Your continued use of the Service following any changes to these Terms constitutes acceptance of those changes.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">2. Eligibility and Age Requirements</h2>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        To use CalorieVision, you must meet the following requirements:
      </p>
      <p className="mb-2 text-sm font-semibold text-muted-foreground md:text-base">General Requirements:</p>
      <ul className="mb-4 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li>Have the legal capacity to enter into a binding agreement</li>
        <li>Not be prohibited from using the Service under applicable laws</li>
      </ul>
      <p className="mb-2 text-sm font-semibold text-muted-foreground md:text-base">Age Requirements:</p>
      <ul className="mb-4 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li><strong>European Union / EEA / UK:</strong> You must be at least 16 years of age, or the age of digital consent in your country if higher</li>
        <li><strong>United States:</strong> You must be at least 13 years of age in compliance with COPPA (Children's Online Privacy Protection Act)</li>
        <li><strong>Other jurisdictions:</strong> You must meet the minimum age requirement in your country</li>
      </ul>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        If you are under the required age, you may only use CalorieVision with the involvement and consent of a parent or legal guardian.
      </p>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        If you are using the Service on behalf of an organization, you represent that you have the authority to bind that organization to these Terms.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">3. Purpose of the Website</h2>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        CalorieVision provides educational tools that allow users to upload images of meals in order to receive estimated calorie information and general nutrition insights. The information provided on this website is for informational and educational purposes only and must not be considered medical, nutritional, or professional advice.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">4. No Medical or Professional Advice</h2>
      <p className="mb-4 text-sm font-bold text-muted-foreground md:text-base">
        IMPORTANT DISCLAIMER: CalorieVision is not a medical service and does not provide medical, dietary, or health advice. Any calorie estimates or nutritional insights generated by the platform are approximate, based on image recognition and standard assumptions, and should not be relied upon for medical decisions.
      </p>
      <ul className="mb-4 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li>All estimates are approximations and may not be accurate</li>
        <li>Results are for educational purposes only</li>
        <li>The Service does not diagnose, treat, or prevent any medical condition</li>
        <li>AI technology has limitations and may produce errors</li>
      </ul>
      <p className="mb-6 text-sm font-semibold text-muted-foreground md:text-base">
        Always consult a qualified healthcare professional, registered dietitian, or nutritionist before making dietary or health-related decisions, especially if you have allergies, medical conditions, or specific nutritional needs.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">5. User Responsibilities</h2>
      <p className="mb-2 text-sm text-muted-foreground md:text-base">
        By using CalorieVision, you agree to:
      </p>
      <ul className="mb-4 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li>Use the website lawfully and respectfully</li>
        <li>Upload only content that you own or have the right to use</li>
        <li>Avoid uploading illegal, harmful, offensive, or misleading content</li>
        <li>Not attempt to disrupt, abuse, or misuse the service</li>
        <li>Not use automated systems (bots, scrapers) to access the Service</li>
        <li>Not attempt to reverse engineer, hack, or compromise the Service</li>
        <li>Provide accurate information when required</li>
        <li>Comply with all applicable local, national, and international laws</li>
      </ul>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        You are solely responsible for the content you upload and how you interpret the results provided.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">6. Accuracy and Limitations</h2>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        While we strive to provide useful and accurate information, CalorieVision does not guarantee the accuracy, completeness, or reliability of any estimates or outputs. Results may vary depending on image quality, lighting conditions, portion visibility, food recognition accuracy, and other factors.
      </p>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        All calorie and nutritional estimates are approximations and may not reflect actual nutritional values. You should not make health decisions based solely on these estimates.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">7. Intellectual Property</h2>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        All content on this website, including text, design, logos, images, software, and underlying technology, is the property of CalorieVision unless otherwise stated. You may not copy, reproduce, distribute, modify, or exploit any part of the website without prior written permission.
      </p>
      <p className="mb-2 text-sm font-semibold text-muted-foreground md:text-base">Your Content:</p>
      <p className="mb-2 text-sm text-muted-foreground md:text-base">
        By uploading photos to CalorieVision, you:
      </p>
      <ul className="mb-6 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li>Retain full ownership of your photos</li>
        <li>Grant us a limited, non-exclusive license to process the image for analysis purposes only</li>
        <li>Acknowledge that photos are processed in real-time and are not stored permanently after analysis</li>
        <li>Confirm you have the right to upload the content</li>
      </ul>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">8. Privacy and Data Protection</h2>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        Your use of this website is governed by our Privacy Policy, which explains how personal data is collected, used, and protected.
      </p>
      <p className="mb-2 text-sm font-semibold text-muted-foreground md:text-base">For users in the European Union, EEA, and UK:</p>
      <p className="mb-2 text-sm text-muted-foreground md:text-base">
        We comply with the General Data Protection Regulation (GDPR) and applicable data protection laws. You have the following rights:
      </p>
      <ul className="mb-4 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li><strong>Right of Access:</strong> Request a copy of your personal data</li>
        <li><strong>Right to Rectification:</strong> Request correction of inaccurate data</li>
        <li><strong>Right to Erasure:</strong> Request deletion of your personal data ("right to be forgotten")</li>
        <li><strong>Right to Restrict Processing:</strong> Request limitation of data processing</li>
        <li><strong>Right to Data Portability:</strong> Receive your data in a portable format</li>
        <li><strong>Right to Object:</strong> Object to certain types of processing</li>
        <li><strong>Right to Withdraw Consent:</strong> Withdraw consent at any time where processing is based on consent</li>
      </ul>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        To exercise these rights, contact us via our Contact page.
      </p>
      <p className="mb-2 text-sm font-semibold text-muted-foreground md:text-base">For users in California, USA:</p>
      <p className="mb-2 text-sm text-muted-foreground md:text-base">
        Under the California Consumer Privacy Act (CCPA), California residents have additional rights including:
      </p>
      <ul className="mb-6 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li>The right to know what personal information is collected</li>
        <li>The right to request deletion of personal information</li>
        <li>The right to opt-out of the sale of personal information (Note: We do not sell personal information)</li>
        <li>The right to non-discrimination for exercising privacy rights</li>
      </ul>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">9. International Data Transfers</h2>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        CalorieVision operates globally. Your information may be transferred to and processed in countries other than your country of residence, including countries that may have different data protection laws.
      </p>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        For users in the EU/EEA/UK, when we transfer data outside these regions, we ensure appropriate safeguards are in place in accordance with GDPR requirements.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">10. Third-Party Services and Links</h2>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        CalorieVision may include links or integrations with third-party services (such as analytics, AI processing, or advertising platforms). We are not responsible for the content, privacy policies, or practices of third-party websites or services.
      </p>
      <p className="mb-2 text-sm text-muted-foreground md:text-base">
        Third-party services we may use include:
      </p>
      <ul className="mb-6 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li>Google Analytics (analytics)</li>
        <li>Google AdSense (advertising)</li>
        <li>AI/ML processing services</li>
        <li>Cloud hosting providers</li>
      </ul>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">11. Advertising</h2>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        This website may display advertisements provided by third-party advertising networks such as Google AdSense or similar platforms. Advertisements are governed by the policies of the respective advertising providers.
      </p>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        Advertising networks may use cookies and similar technologies to serve relevant ads. You can manage your advertising preferences through your browser settings or our cookie consent tool.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">12. Disclaimer of Warranties</h2>
      <p className="mb-4 text-sm font-semibold text-muted-foreground md:text-base">
        THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.
      </p>
      <p className="mb-2 text-sm text-muted-foreground md:text-base">
        TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, WE DISCLAIM ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO:
      </p>
      <ul className="mb-4 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li>Implied warranties of merchantability</li>
        <li>Fitness for a particular purpose</li>
        <li>Non-infringement</li>
        <li>Accuracy or reliability of results</li>
        <li>Uninterrupted or error-free service</li>
        <li>Security of the Service</li>
      </ul>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        Some jurisdictions do not allow the exclusion of certain warranties, so some of the above exclusions may not apply to you.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">13. Limitation of Liability</h2>
      <p className="mb-2 text-sm text-muted-foreground md:text-base">
        TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, CalorieVision, its owners, employees, affiliates, and partners shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from:
      </p>
      <ul className="mb-4 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li>Use or inability to use the website</li>
        <li>Reliance on any information or estimates provided</li>
        <li>Errors, interruptions, or inaccuracies</li>
        <li>Any decisions made based on the Service's estimates</li>
        <li>Unauthorized access to your data</li>
        <li>Any third-party conduct or content</li>
        <li>Any health-related consequences from using estimates</li>
      </ul>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        Use of the website is at your own risk.
      </p>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        <strong>Liability Cap:</strong> Our total liability for any claims arising from the Service shall not exceed the greater of (a) the amount you paid to us in the 12 months preceding the claim, or (b) $100 USD.
      </p>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        <strong>EU/UK Users:</strong> Nothing in these Terms shall limit or exclude our liability for death or personal injury caused by our negligence, fraud or fraudulent misrepresentation, or any other liability that cannot be limited or excluded by applicable law.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">14. Indemnification</h2>
      <p className="mb-2 text-sm text-muted-foreground md:text-base">
        To the extent permitted by applicable law, you agree to indemnify, defend, and hold harmless CalorieVision, its owners, employees, and affiliates from any claims, damages, losses, liabilities, costs, and expenses (including reasonable legal fees) arising from:
      </p>
      <ul className="mb-6 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li>Your use of the Service</li>
        <li>Your violation of these Terms</li>
        <li>Your violation of any third-party rights</li>
        <li>Any content you submit through the Service</li>
        <li>Your violation of any applicable laws</li>
      </ul>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">15. Dispute Resolution</h2>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        <strong>Informal Resolution:</strong> Before filing any formal legal claim, you agree to contact us first and attempt to resolve the dispute informally for at least 30 days.
      </p>
      <p className="mb-2 text-sm font-semibold text-muted-foreground md:text-base">For users in the United States:</p>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        Any disputes arising from these Terms or the Service that cannot be resolved informally shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association (AAA), rather than in court.
      </p>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        <strong>Class Action Waiver:</strong> You agree to resolve disputes with us on an individual basis and waive any right to participate in a class action lawsuit or class-wide arbitration.
      </p>
      <p className="mb-2 text-sm font-semibold text-muted-foreground md:text-base">For users in the European Union/EEA/UK:</p>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        Nothing in these Terms affects your statutory rights as a consumer. You may bring legal proceedings in your country of residence. You may also use the EU Online Dispute Resolution platform at <a href="https://ec.europa.eu/consumers/odr/" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">https://ec.europa.eu/consumers/odr/</a>
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">16. Modifications to the Terms</h2>
      <p className="mb-2 text-sm text-muted-foreground md:text-base">
        We reserve the right to update or modify these Terms and Conditions at any time. When we make changes:
      </p>
      <ul className="mb-4 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li>We will update the "Last updated" date at the top</li>
        <li>For material changes, we may notify users via the website or email</li>
        <li>Changes will be effective immediately upon publication</li>
      </ul>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        Continued use of the website after changes constitutes acceptance of the updated terms. We encourage you to review these Terms periodically.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">17. Termination</h2>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        <strong>By You:</strong> You may stop using the Service at any time.
      </p>
      <p className="mb-2 text-sm text-muted-foreground md:text-base">
        <strong>By Us:</strong> We may terminate or suspend your access to the Service immediately, without prior notice, if:
      </p>
      <ul className="mb-4 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li>You breach any provision of these Terms</li>
        <li>We are required to do so by law</li>
        <li>We decide to discontinue the Service</li>
        <li>We detect fraudulent or abusive behavior</li>
      </ul>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        Upon termination, your right to use the Service will immediately cease. Sections of these Terms that by their nature should survive termination (including Disclaimers, Limitation of Liability, and Indemnification) will survive.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">18. Governing Law and Jurisdiction</h2>
      <p className="mb-2 text-sm font-semibold text-muted-foreground md:text-base">For users in the European Union/EEA/UK:</p>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        These Terms shall be governed by the laws of your country of residence. You have the right to bring legal proceedings in your local courts.
      </p>
      <p className="mb-2 text-sm font-semibold text-muted-foreground md:text-base">For users in the United States:</p>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        These Terms shall be governed by the laws of the State of Delaware, USA, without regard to conflict of law principles.
      </p>
      <p className="mb-2 text-sm font-semibold text-muted-foreground md:text-base">For users in other jurisdictions:</p>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        These Terms shall be governed by the laws applicable in your jurisdiction, to the extent they provide mandatory consumer protections.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">19. Severability</h2>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        If any provision of these Terms is found to be unenforceable or invalid by a court of competent jurisdiction, that provision will be limited or eliminated to the minimum extent necessary, and the remaining provisions will remain in full force and effect.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">20. Entire Agreement</h2>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        These Terms, together with our Privacy Policy, Cookie Policy, and Disclaimer, constitute the entire agreement between you and CalorieVision regarding your use of the Service and supersede any prior agreements.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">21. No Waiver</h2>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. Any waiver must be in writing and signed by CalorieVision to be effective.
      </p>

      <hr className="my-8 border-border" />

      <h2 className="mb-2 text-xl font-semibold">22. Contact Information</h2>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        If you have any questions regarding these Terms and Conditions, please contact us:
      </p>
      <ul className="mb-4 list-disc space-y-1 pl-5 text-sm text-muted-foreground md:text-base">
        <li><strong>Website:</strong> <a href="https://calorievision.online" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">calorievision.online</a></li>
        <li><strong>Contact Page:</strong> <a href="https://calorievision.online/contact" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">calorievision.online/contact</a></li>
      </ul>
      <p className="mb-2 text-sm font-semibold text-muted-foreground md:text-base">For GDPR/Privacy inquiries (EU/UK users):</p>
      <p className="mb-4 text-sm text-muted-foreground md:text-base">
        Please use our Contact page and specify "GDPR Request" or "Privacy Request" in your message.
      </p>
      <p className="mb-2 text-sm font-semibold text-muted-foreground md:text-base">For CCPA inquiries (California residents):</p>
      <p className="mb-6 text-sm text-muted-foreground md:text-base">
        Please use our Contact page and specify "CCPA Request" in your message.
      </p>

      <hr className="my-8 border-border" />

      <p className="text-sm italic text-muted-foreground md:text-base">
        By using CalorieVision, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions.
      </p>
    </LegalPageWrapper>
  );
};

export default Terms;
